name: Tertiary FD Defense (15m PT)

on:
  workflow_dispatch:
  schedule:
    # Runs at :11/:26/:41/:56 each hour (UTC). We'll gate to LA hours below.
    - cron: "11,26,41,56 * * * *"

permissions:
  contents: read

jobs:
  run-tertiary-defense:
    runs-on: ubuntu-latest

    env:
      # ----- App config -----
      GCP_PROJECT: sac-vald-hub
      BQ_DATASET: analytics
      BQ_LOCATION: US

      # Mirror secrets into env so we can safely reference in `if:` conditions
      GCP_SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
      FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
      TO_EMAIL:   ${{ secrets.TO_EMAIL }}
      SMTP_HOST:  ${{ secrets.SMTP_HOST }}
      SMTP_PORT:  ${{ secrets.SMTP_PORT }}
      SMTP_USER:  ${{ secrets.SMTP_USER }}
      SMTP_PASS:  ${{ secrets.SMTP_PASS }}

      VALD_CLIENT_ID:     ${{ secrets.VALD_CLIENT_ID }}
      VALD_CLIENT_SECRET: ${{ secrets.VALD_CLIENT_SECRET }}
      VALD_TENANT_ID:     ${{ secrets.VALD_TENANT_ID }}
      VALD_REGION:        use

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo UTC and LA time
        run: |
          echo "UTC now: $(date -u)"
          echo "LA  now: $(TZ=America/Los_Angeles date)"

      # ---- Gate by Pacific Time (06:11–19:56 PT every 15 minutes) ----
       - name: Gate to 06:00–19:59 PT
        id: gate
        shell: bash
        run: |
          LA_HOUR=$(TZ=America/Los_Angeles date +%H)
          if [ "$LA_HOUR" -ge 6 ] && [ "$LA_HOUR" -lt 20 ]; then
            echo "outside_window=false" >> "$GITHUB_OUTPUT"
            echo "Proceeding (within 06:00–19:59 PT)."
          else
            echo "outside_window=true" >> "$GITHUB_OUTPUT"
            echo "Outside 06:00–19:59 PT – skipping."
          fi

          case "$LA_MIN" in
            11|26|41|56) echo "outside_window=false" >> "$GITHUB_OUTPUT" ;;
            *)           echo "outside_window=true"  >> "$GITHUB_OUTPUT" ;;
          esac

      - name: Stop if outside LA window
        if: ${{ steps.gate.outputs.outside_window == 'true' }}
        run: echo "Skipping this tick (outside 06:11–20:00 PT cadence)."

      # ---- Google auth (only if key present) ----
      - name: Google Auth (service account key)
        if: ${{ steps.gate.outputs.outside_window == 'false' && env.GCP_SA_KEY_JSON != '' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY_JSON }}

      - name: Setup gcloud (optional)
        if: ${{ steps.gate.outputs.outside_window == 'false' }}
        uses: google-github-actions/setup-gcloud@v2

      # ---- R setup & deps ----
      - name: Setup R
        if: ${{ steps.gate.outputs.outside_window == 'false' }}
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages (cached)
        if: ${{ steps.gate.outputs.outside_window == 'false' }}
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          use-public-rspm: true
          extra-packages: >
            any::bigrquery
            any::DBI
            any::dplyr
            any::tidyr
            any::readr
            any::stringr
            any::purrr
            any::tibble
            any::data.table
            any::hms
            any::lubridate
            any::httr
            any::jsonlite
            any::xml2
            any::curl
            any::gargle
            any::rlang
            any::lifecycle
            any::glue
            any::valdr

      # ---- Run the tertiary defense script at the new path ----
      - name: Run tertiary defense
        if: ${{ steps.gate.outputs.outside_window == 'false' }}
        run: |
          chmod +x .github/scripts/tertiary_fd_defense.R
          .github/scripts/tertiary_fd_defense.R
